server:
  port: 8085
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Saurabh7076/micro-config-service
          clone-on-start: true
